jongsul_jango-master/books/books/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from books import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^usermanage/', include(('usermanage.urls','usernamage'),namespace="usermanage")),
    url(r'^check/', include(('check.urls','check'),namespace="check")),
    url(r'^reservation/', include(('reservation.urls','revervation'), namespace="reservation")),
    #   reservation result url 작성부탁드려요. 그리고 이 url base.html에 reservation result라고 써진부분에 넣어주세요.

]

jongsul_jango-master/books/check/urls.py
from django.conf.urls import url
from check import views

urlpatterns = [
    url(r'^$', views.checkPageView.as_view(), name='check'),
    url(r'checkresult/$',views.checkResultPageView.as_view(), name='check_result'),
]

jongsul_jango-master/books/reservation/urls.py
from django.conf.urls import url
from reservation import views

urlpatterns = [
    url(r'^$', views.reservationPageView.as_view(), name='index'),
    url(r'^reservation_result/$', views.reservationResultPageView.as_view(), name='reservation_result'),
]

jongsul_jango-master/books/usermanage/urls.py
from django.conf.urls import url
from usermanage import views

urlpatterns = [
    url(r'^$', views.LoginPageView.as_view(), name='login'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signin/join/$',views.signup, name='join'),
]

jongsul_jango-master/books/check/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    apoti_true = models.IntegerField()
    log_date = models.DateTimeField()

jongsul_jango-master/books/polls/models.py
from django.db import models

# Create your models here.

jongsul_jango-master/books/reservation/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Hospital(models.Model):
    name = models.CharField(max_length=100)
    call = models.CharField(max_length=100)
    location = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name

class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reservation_date = models.DateField()
    hospital = models.CharField(max_length=100)

    def __unicode__(self):
        return self.user

jongsul_jango-master/books/usermanage/models.py
from django.db import models

# Create your models here.

jongsul_jango-master/books/books/views.py
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        return context

jongsul_jango-master/books/check/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView

# Create your views here.
class checkPageView(TemplateView):
    template_name = 'check/check.html'

    def get_context_data(self, **kwargs):
        context = super(checkPageView, self).get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        #판단 알고리즘..

        return render(request,'check/check_result.html')


class checkResultPageView(TemplateView):
    def get(self, request, *args, **kwargs):
        return render(request, 'check/check_result.html')

jongsul_jango-master/books/polls/views.py
from django.shortcuts import render

# Create your views here.

jongsul_jango-master/books/reservation/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from .models import Hospital, Reservation
from django import forms
# Create your views here.
class reservationPageView(TemplateView):
    def get(self, request, *args, **kwargs):
        form = ReservationForm()
        return render(request, 'reservation/index.html',{'form':form})

    def post(self, request, *args, **kwargs):
        #reservation 추가

        user = request.POST['user']
        reservation_date = request.POST['reservation_date']
        hospital = request.POST['hospital']

        reservation = Reservation(user=user,reservation_date=reservation_date,hospital=hospital)
        reservation.save()

        return redirect('reservation/')

class reservationResultPageView(TemplateView):
    def get(self, request, *args, **kwargs):
        try:
            reservation_all = Reservation.objects.all()
            reservation_bind = {'reservation_all': reservation_all}
            return render(request, 'reservation/reservation_result.html', reservation_bind)
        except:
            return redirect('reservation/')

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['user','reservation_date','hospital']

jongsul_jango-master/books/usermanage/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from django.http import HttpResponse, HttpResponseRedirect
# Create your views here.
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.template import RequestContext

class LoginPageView(TemplateView):
    template_name = 'usermanage/login.html'

    def get_context_data(self, **kwargs):
        context = super(LoginPageView, self).get_context_data(**kwargs)
        return context

class SigninPageView(TemplateView):
    template_name = 'usermanage/signin.html'

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','password']

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(**form.cleaned_data)
            login(request, new_user)
            return redirect('home')
    else:
        form = UserForm()
        return render(request,'usermanage/signin.html',{'form':form})

def signin(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        username=request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            return HttpResponse('로그인 실패, 다시 시도해 보세요')

    else:
        form = LoginForm()
        return render(request,'usermanage/login.html',{'form':form})

jongsul_jango-master/books/check/templates/check/check.html
{%  extends "home.html" %}

{% block content %}

	<section style="width:50%;margin:40px auto; background-color: white;">
			<fieldset style="height: 350px">
				<legend> 진료사진 업로드</legend>.
                <form method="post" action="{% url 'check:check' %}">
				{%  csrf_token %}
                    <input id="file-upload" type="file" multiple><br>
				<input type="submit" value="제출" style="margin-top: 290px; margin-left: 90%">
                </form>
			</fieldset>
		</section>

{% endblock content %}

jongsul_jango-master/books/check/templates/check/check_result.html
{%  extends  'home.html'%}

{% block content %}
<center >
<section style="width:50%;margin:100px;margin-left:200px; background-color: white;">
      {%  csrf_token %}
    <li>진단 결과는   ...입니다.<br>
        <a href="{% url 'reservation:index' %}">예약하시겠습니까?</a></li>
</section>
</center>

{% endblock content %}

jongsul_jango-master/books/reservation/templates/reservation/index.html
{% extends 'home.html' %}

<!-- 예약 폼 -->
{% block content%}

        <form method="post" action="{% url 'reservation:reservation_result' %}" id="thisform"  style="margin-right : 70%; background-color: white;">
          {% csrf_token %}
         {{ form.as_p }}
            <input type="submit" value="예약하기" />
        </form>

{% endblock content %}

jongsul_jango-master/books/reservation/templates/reservation/reservation_result.html
{% extends 'home.html' %}

{% block content %}

     <h2>reservation _list</h2>
        <ul>
        {% for reservation in reservation_all %}
        <h3><li>{{ reservation.user }} : {{ reservation.reservation_date }} : {{ reservation.hospital }}</li></h3>
        {% endfor %}
        </ul>

{% endblock content %}

jongsul_jango-master/books/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/base_css.css' %}"/>
{% endblock css %}

    <meta charset="UTF-8">
    <title>{% block title %}hello A_Team{% endblock %}</title>

    {% block login_script %}

    {% endblock login_script %}

</head>
<body>

        <header>
			<div class="logo">
                <a href="/">
				<img src="{% static 'images/logo.png' %}"><!--로고이미지url이 들어갑니다. -->
				</a>
			</div>

			<h1>A_TEAM RESULT</h1>
		</header>

    <div id="sidebar">
        {% block sidebar %}
             <div class="nav">
			<ul>
				<li id="nav1">
					<a href="#">로그인/회원가입</a>
					<div>
						<a href="/">로그인</a>
						<a href="/">회원가입</a>
					</div>
				</li>
				<li id="nav2">
					<a href="/">질병확인하기</a>
				</li>
				<li id="nav3">
					<a href="/">병원 예약하기</a>
				</li>
			</ul>
		</div>
        {% endblock %}
    </div>
	{% if user.username %}

<h4 align="right">{{user.username}} 님 반갑습니다.</h4>

{% else %}

<h4 align="right"><a href="/accounts/login">로그인</a>하세요</h4>

{% endif %}
    <section id="content" style="background-color: white">
        {% block content %}

        {% endblock content %}
    </section>
	<aside id="side">
		{% block side %}
		<li>
			<a href="reservation_result"> 마이페이지</a>
		</li>
		<li>
			<a>예약</a>
		</li>
		{% endblock side %}
	</aside>
<footer>
			Copyright &copy; 2018 A_TEAM RESULT PAGE.
</footer>

</body>
</html>

jongsul_jango-master/books/templates/base_usermanage.html
{% extends "base.html" %}

jongsul_jango-master/books/templates/home.html
{% extends "base.html" %}

 {% block login_script %}

    <script type="text/javascript">
			window.onload=function(){
				var nav1 = document.getElementById('nav1');
				nav1.addEventListener("click", function(){
					var child = this.querySelector("div");
					child.style.display = "block"
				});
				var nav1 = document.getElementById('nav1');
				nav1.addEventListener("mouseleave", function(){
					var child = this.querySelector("div");
					child.style.display = "none"
				});
			}
		</script>
 {% endblock login_script %}


 {% block sidebar %}
             <div class="nav">
			<ul>
				<li id="nav1">
					<a href="#">로그인/회원가입</a>
					<div>
						<a href="{% url 'usermanage:signin' %}">로그인</a>
						<a href="{% url 'usermanage:join' %}">회원가입</a>
					</div>
				</li>
				<li id="nav2">
					<a href="{% url 'check:check' %}">질병확인하기</a>
				</li>
				<li id="nav3">
					<a href="{% url 'reservation:index' %}">병원 예약하기</a>
				</li>
			</ul>
		</div>
        {% endblock %}

jongsul_jango-master/books/usermanage/templates/usermanage/login.html
{% extends "home.html" %}

{% block css %}
{{ block.super }}
    {% load static %}
 <link rel="stylesheet" type="text/css" href="{% static 'usermanage/login.css' %}"/>
{% endblock css %}



{% block content %}

   <section  style=" background-color: white;">
        <form method="post" action="{% url 'usermanage:signin' %}" id="thisform" style="width:50%;margin:100px;margin-left:300px; background-color: white;">
          {% csrf_token %}
         {{ form.as_p }}
            <input type="submit" value="로그인" />
        </form>

   </section>

{% endblock content %}

jongsul_jango-master/books/usermanage/templates/usermanage/signin.html
{% extends "home.html" %}

{% block css %}
{{ block.super }}
    {% load static %}
 <link rel="stylesheet" type="text/css" href="{% static 'usermanage/login.css' %}"/>
{% endblock css %}


{% block content %}

<section style="background-color: white;">
	<form method="post" action="{% url 'usermanage:join' %}"  style="width:50%;margin:100px;margin-left:400px; background-color: white;">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="회원가입"/>
        <input type="button" value="돌아가기"/>
    </form>
    <!--
			<form id="new" method="get">
			<table>
				<tr>
				<td>아이디</td>
				<td><input type="text" name="id"></td>
				<td><input type="button" id="same" value="중복확인"></td>
				</tr>
				<tr>
				<td>비밀번호</td>
				<td><input type="password" name="pwd"></td>
				</tr>
				<tr>
				<td>비밀번호 확인</td>
				<td><input type="password" name="pwd2"></td>
				</tr>
				<tr>
				<td>이름</td>
				<td><input type="text" name="name"></td>
				</tr>
				<tr>
				<td>전화번호</td>
				<td><input type="text" name="number"></td>
				</tr>
				<tr>
				<td>생년월일</td>
				<td><input type="date" id="birth" name="birth"></td>
				</tr>
				<tr>
				<td>성별</td>
				<td><input type="radio" name="sex" value="male">남자<input type="radio" name="sex" value="female">여자</td>
				</tr>
				<tr>
				<td>이메일</td>
				<td><input type="text" name="email">@
				<select name="mail">
				<option value="naver">naver.com</option>
				<option value="daum">hanmail.net</option>
				<option value="google">gmail.com</option>
				</select></td>
				</tr>
				<tr>
				<td>앓고있는 질병</td>
				<td><input type="text", name="disease"></td>
				</tr>
				<tr>
				<td>개인정보이용에 동의하십니까?</td>
				<td><input type="radio" name="agreement" value="yes">예<input type="radio" name="agreement" value="no">아니오</td>
				</tr>
				<tr>
				<td colspan="2">
				<input type="submit" id="sign" value="완료">
				<input type="button" id="back" value="돌아가기" onclick="location.href='file:///C:/Users/HusnSooKim/Desktop/main.html'">
				</td>
				</tr>
				</table>
			</form>
			-->
		</section>
{% endblock content %}